services:
  db:
    image: mysql:8.0
    command: --default-authentication-plugin=mysql_native_password
    restart: unless-stopped
    env_file: .env
    ports:
      - 3396:3306
    volumes:
      - db-data:/var/lib/mysql
      - ./etc/docker/initdb.d:/docker-entrypoint-initdb.d

  drupal:
    image: drupal
    build:
      context: etc/docker
    env_file: .env
    ports:
      - 81:80
    volumes:
      - ./web:/opt/drupal/web
    depends_on: [db]

volumes:
  db-data:

# openssl aes-256-cbc -d -a -in $(ls -rt etc/ansible/playbooks/backups/dev/var/tmp/dumps/*.sql.gz.enc) -out .docker/initdb.d/dump.sql -pass pass:$(cat .crypt-password)
# mysql -uroot -p${MYSQL_ROOT_PASSWORD} -P3396 -h127.0.0.1 -e "drop database ${MYSQL_DATABASE}"
# mysql -uroot -p${MYSQL_ROOT_PASSWORD} -P3396 -h127.0.0.1 -e "CREATE DATABASE IF NOT EXISTS ${MYSQL_DATABASE}"
# mysql -uroot -p${MYSQL_ROOT_PASSWORD} -P3396 -h127.0.0.1 drupal < /tmp/dump.sql
# drush cr
