services:
  db:
    image: mysql:8.0
    command: --default-authentication-plugin=mysql_native_password
    restart: unless-stopped
    env_file: .env
    ports:
      - 3396:3306
    volumes:
      - db-data:/var/lib/mysql
      - ./etc/docker/initdb.d:/docker-entrypoint-initdb.d

  drupal:
    image: drupal
    build:
      context: etc/docker
    env_file: .env
    ports:
      - 81:80
    volumes:
      - ./web:/opt/drupal/web
    depends_on: [db]
    restart: unless-stopped

volumes:
  db-data:

# source .env
# mysql -u${MYSQL_USER} -p${MYSQL_PASSWORD} -P3396 -h127.0.0.1 -e "drop database ${MYSQL_DATABASE}"
# mysql -u${MYSQL_USER} -p${MYSQL_PASSWORD} -P3396 -h127.0.0.1 -e "CREATE DATABASE IF NOT EXISTS ${MYSQL_DATABASE}"
# mysql -u${MYSQL_USER} -p${MYSQL_PASSWORD} -P3396 -h127.0.1 drupal < etc/docker/initdb.d/dump.sql
# docker compose exec drupal /opt/drupal/vendor/bin/drush cr
#
# docker compose exec drupal /opt/drupal/vendor/bin/drush upwd $USER password
#  or
# docker compose exec drupal /opt/drupal/vendor/bin/drush user:create $USER --mail='$USER@$HOSTNAME' --password='password'
