<?php

/**
 * @file
 * Primary module hooks for NRFC League table scraper module.
 */

function nrfc_league_table_scraper_cron()
{
//  $today = date("z");
//  $lastRun = \Drupal::state()->get('nrfc_league_table_scraper_last_run', -1);
//  if ((int)$today > (int)$lastRun) {
//    \Drupal::state()->set('nrfc_league_table_scraper_last_run', (int)$today);
//  }
  \Drupal::logger('nrfc_league_table_scraper')->info("Running Cron for NRFC League scrapper");
  \Drupal::service('nrfc_league_table_scraper_engine')->updateAll();
}

/**
 * Implements hook_theme().
 */
function nrfc_league_table_scraper_theme() {
  return [
    'nrfc_league_table_scraper' => [
      'variables' => [
        'rows' => [],
      ],
    ],
  ];
}
