- name: Playbook to dump SQL db
  hosts: myservers

  tasks:
    -

    - name: Set NOW
      set_fact:
        now: "{{ ansible_date_time.iso8601 | replace(':','_') }}"
    -
    - name: Set dump dir
      set_fact:
        dump_dir: "/var/tmp/dumps/{{ now }}"

    - name: Set file names
      set_fact:
        dump_file: "{{ dump_dir }}/dump.sql.gz.enc"
        files_dir: "{{ dump_dir }}/files"
        archive_file: "/tmp/{{ now }}.tgz"

    - name: Ensure dump dir & files
      file:
        path: "{{ item }}"
        state: directory
        mode: '0755'
      with_items:
        - "{{ dump_dir }}"
        - "{{ files_dir }}"

    - name: Dump MySQL database and encrypt without writing to disk
      shell: >
        docker compose -f /opt/docker/drupal/docker-compose.yml exec mysql \
        mysqldump \
          --single-transaction \
          --quick \
          --lock-tables=false \
          --databases {{ db_name }} \
          --host 127.0.0.1 \
          --user=root \
          --password={{ db_root_password }} \
          | \
          gzip \
          | \
          openssl aes-256-cbc \
            -out "{{ dump_file }}" \
            -pbkdf2 \
            -pass pass:{{ db_crypt_password }}

    - name: Get the fies from docker
      shell: >
        docker cp drupal-drupal-1:/opt/drupal/web/sites/default/files {{ files_dir }}

    - name: compress the files
      shell: >
        tar -C {{ dump_dir }} -zcvf {{ archive_file }} .

    - name: Get the backup
      fetch:
        src: "{{ archive_file }}"
        dest: backups
