# Schema for the configuration files of the Bootstrap Barrio Subtheme.

nrfc_barrio.settings:
  type: config_object
  label: 'NRFC Barrio theme settings'
  mapping:
    nrfc_barrio_library:
      type: string
      label: 'My Custom Setting'
    nrfc_barrio_sidebar_position:
      type: string
      label: 'Another Setting'
    nrfc_barrio_content_offset:
      type: integer
      label: 'Another Setting'
    nrfc_barrio_sidebar_first_width:
      type: integer
      label: 'Another Setting'
    nrfc_barrio_sidebar_first_offset:
      type: integer
      label: 'Another Setting'
    nrfc_barrio_sidebar_second_width:
      type: integer
      label: 'Another Setting'
    nrfc_barrio_sidebar_second_offset:
      type: integer
      label: 'Another Setting'
    nrfc_barrio_fluid_container:
      type: integer
      label: 'Another Setting'
    nrfc_barrio_button:
      type: integer
      label: 'Another Setting'
    nrfc_barrio_button_size:
      type: string
      label: 'Another Setting'
    nrfc_barrio_button_outline:
      type: integer
      label: 'Another Setting'
    nrfc_barrio_navbar_toggle:
      type: string
      label: 'Another Setting'
    nrfc_barrio_navbar_container:
      type: string
      label: 'Another Setting'
    nrfc_barrio_navbar_top_position:
      type: string
      label: 'Another Setting'
    nrfc_barrio_navbar_top_color:
      type: string
      label: 'Another Setting'
    nrfc_barrio_navbar_top_background:
      type: string
      label: 'Another Setting'
    nrfc_barrio_navbar_position:
      type: string
      label: 'Another Setting'
    nrfc_barrio_navbar_color:
      type: string
      label: 'Another Setting'
    nrfc_barrio_navbar_background:
      type: string
      label: 'Another Setting'
    nrfc_barrio_messages_widget:
      type: string
      label: 'Another Setting'
    nrfc_barrio_radio:
      type: string
      label: 'Another Setting'
    nrfc_barrio_checkbox:
      type: string
      label: 'Another Setting'
    nrfc_barrio_select:
      type: string
      label: 'Another Setting'
    nrfc_barrio_file:
      type: string
      label: 'Another Setting'
    nrfc_barrio_system_messages:
      type: string
      label: 'Another Setting'
    nrfc_barrio_table_hover:
      type: integer
      label: 'Another Setting'
    nrfc_barrio_table_style:
      type: string
      label: 'Another Setting'

nrfc_barrio_settings:
  type: theme_settings
  label: 'NRFC Barrio settings'

nrfc_barrio_sass.settings:
  type: theme_settings
  label: 'Bootstrap Barrio settings'
  mapping:

# Library.
# ----------------------------
nrfc_barrio_library:
  type: text
  label: 'Load library'

# Container.
# ----------------------------
nrfc_barrio_fluid_container:
  type: integer
  label: 'Fluid container'

# Region.
# ----------------------------
nrfc_barrio_region_clean_top_header:
  type: text
  label: 'Clean wrapper for Top header region'
nrfc_barrio_region_class_top_header:
  type: text
  label: 'Classes for Top header region'
nrfc_barrio_region_clean_top_header_form:
  type: text
  label: 'Clean wrapper for Top header form region'
nrfc_barrio_region_class_top_header_form:
  type: text
  label: 'Classes for Top header form region'
nrfc_barrio_region_clean_header:
  type: text
  label: 'Clean wrapper for Header region'
nrfc_barrio_region_class_header:
  type: text
  label: 'Classes for Header region'
nrfc_barrio_region_clean_header_form:
  type: text
  label: 'Clean wrapper for Header form region'
nrfc_barrio_region_class_header_form:
  type: text
  label: 'Classes for Header form region'
nrfc_barrio_region_clean_primary_menu:
  type: text
  label: 'Clean wrapper for Primary menu region'
nrfc_barrio_region_class_primary_menu:
  type: text
  label: 'Classes for Primary menu region'
nrfc_barrio_region_clean_secondary_menu:
  type: text
  label: 'Clean wrapper for Secondary menu region'
nrfc_barrio_region_class_secondary_menu:
  type: text
  label: 'Classes for Secondary menu region'
nrfc_barrio_region_clean_page_top:
  type: text
  label: 'Clean wrapper for Page top region'
nrfc_barrio_region_class_page_top:
  type: text
  label: 'Classes for Page top region'
nrfc_barrio_region_clean_page_bottom:
  type: text
  label: 'Clean wrapper for Page bottom region'
nrfc_barrio_region_class_page_bottom:
  type: text
  label: 'Classes for Page bottom region'
nrfc_barrio_region_clean_highlighted:
  type: text
  label: 'Clean wrapper for Highlighted region'
nrfc_barrio_region_class_highlighted:
  type: text
  label: 'Classes for Highlighted region'
nrfc_barrio_region_clean_featured_top:
  type: text
  label: 'Clean wrapper for Featured top region'
nrfc_barrio_region_class_featured_top:
  type: text
  label: 'Classes for Featured top region'
nrfc_barrio_region_clean_breadcrumb:
  type: text
  label: 'Clean wrapper for Breadcrumb region'
nrfc_barrio_region_class_breadcrumb:
  type: text
  label: 'Classes for Breadcrumb region'
nrfc_barrio_region_clean_content:
  type: text
  label: 'Clean wrapper for Content region'
nrfc_barrio_region_class_content:
  type: text
  label: 'Classes for Content region'
nrfc_barrio_region_clean_sidebar_first:
  type: text
  label: 'Clean wrapper for Sidebar first region'
nrfc_barrio_region_class_sidebar_first:
  type: text
  label: 'Classes for Sidebar first region'
nrfc_barrio_region_clean_sidebar_second:
  type: text
  label: 'Clean wrapper for Sidebar second region'
nrfc_barrio_region_class_sidebar_second:
  type: text
  label: 'Classes for Sidebar second region'
nrfc_barrio_region_clean_featured_bottom_first:
  type: text
  label: 'Clean wrapper for Featured bottom first region'
nrfc_barrio_region_class_featured_bottom_first:
  type: text
  label: 'Classes for Featured bottom first region'
nrfc_barrio_region_clean_featured_bottom_second:
  type: text
  label: 'Clean wrapper for Featured bottom second region'
nrfc_barrio_region_class_featured_bottom_second:
  type: text
  label: 'Classes for Featured bottom second region'
nrfc_barrio_region_clean_featured_bottom_third:
  type: text
  label: 'Clean wrapper for Featured bottom third region'
nrfc_barrio_region_class_featured_bottom_third:
  type: text
  label: 'Classes for Featured bottom third region'
nrfc_barrio_region_clean_footer_first:
  type: text
  label: 'Clean wrapper for Footer first region'
nrfc_barrio_region_class_footer_first:
  type: text
  label: 'Classes for Footer first region'
nrfc_barrio_region_clean_footer_second:
  type: text
  label: 'Clean wrapper for Footer second region'
nrfc_barrio_region_class_footer_second:
  type: text
  label: 'Classes for Footer second region'
nrfc_barrio_region_clean_footer_third:
  type: text
  label: 'Clean wrapper for Footer third region'
nrfc_barrio_region_class_footer_third:
  type: text
  label: 'Classes for Footer third region'
nrfc_barrio_region_clean_footer_fourth:
  type: text
  label: 'Clean wrapper for Footer fourth region'
nrfc_barrio_region_class_footer_fourth:
  type: text
  label: 'Classes for Footer fourth region'
nrfc_barrio_region_clean_footer_fifth:
  type: text
  label: 'Clean wrapper for Footer fifth region'
nrfc_barrio_region_class_footer_fifth:
  type: text
  label: 'Classes for Footer fifth region'

# Sidebar position.
# ----------------------------
nrfc_barrio_sidebar_position:
  type: text
  label: 'Sidebar position'
nrfc_barrio_content_offset:
  type: integer
  label: 'Content offset'

# Sidebar first layout.
# ----------------------------
nrfc_barrio_sidebar_collapse:
  type: integer
  label: 'Sidebar collapse'
nrfc_barrio_sidebar_first_width:
  type: integer
  label: 'Sidebar first width'
nrfc_barrio_sidebar_first_offset:
  type: integer
  label: 'Sidebar first offset'

# Sidebar second layout.
# ----------------------------
nrfc_barrio_sidebar_second_width:
  type: integer
  label: 'Sidebar second width'
nrfc_barrio_sidebar_second_offset:
  type: integer
  label: 'Sidebar second layout'

# Buttons.
# ----------------------------
nrfc_barrio_button:
  type: integer
  label: 'Convert input submit to button element'
nrfc_barrio_button_size:
  type: text
  label: 'Default button size'
nrfc_barrio_button_outline:
  type: integer
  label: 'Button with outline format'

# Navbar.
# ----------------------------
nrfc_barrio_navbar_container:
  type: text
  label: 'Navbar width container'
nrfc_barrio_navbar_toggle:
  type: text
  label: 'Navbar toggle size'
nrfc_barrio_navbar_top_navbar:
  type: integer
  label: 'Navbar top is navbar'
nrfc_barrio_navbar_top_position:
  type: text
  label: 'Navbar top position'
nrfc_barrio_navbar_top_color:
  type: text
  label: 'Navbar top link color'
nrfc_barrio_navbar_top_background:
  type: text
  label: 'Navbar top background color'
nrfc_barrio_navbar_position:
  type: text
  label: 'Navbar position'
nrfc_barrio_navbar_color:
  type: text
  label: 'Navbar link color'
nrfc_barrio_navbar_background:
  type: text
  label: 'Navbar background color'

# Messages.
# ----------------------------
nrfc_barrio_messages_widget:
  type: text
  label: 'Messages widget'

# Form.
# ----------------------------
nrfc_barrio_radio:
  type: text
  label: 'Radio widget'
nrfc_barrio_checkbox:
  type: text
  label: 'Checkbox widget'
nrfc_barrio_select:
  type: text
  label: 'Select widget'
nrfc_barrio_file:
  type: text
  label: 'File widget'

# Affix.
# ----------------------------
nrfc_barrio_navbar_top_affix:
  type: integer
  label: 'Affix navbar top'
nrfc_barrio_navbar_affix:
  type: integer
  label: 'Affix navbar'
nrfc_barrio_sidebar_first_affix:
  type: integer
  label: 'Affix sidebar first'
nrfc_barrio_sidebar_second_affix:
  type: integer
  label: 'Affix sidebar first'

# Scrollspy.
# ----------------------------
nrfc_barrio_scroll_spy:
  type: text
  label: 'Scrollspy element ID'

# Fonts.
# ----------------------------
nrfc_barrio_google_fonts:
  type: text
  label: 'Google Fonts combination'

# Icons.
# ----------------------------
nrfc_barrio_icons:
  type: text
  label: 'Icon set'

# System messages.
# ----------------------------
nrfc_barrio_system_messages:
  type: text
  label: 'System messages color scheme'

# Tables.
# ----------------------------
nrfc_barrio_table_style:
  type: text
  label: 'Table cell style'
nrfc_barrio_table_hover:
  type: integer
  label: 'Hover effect over table cells'
nrfc_barrio_table_head:
  type: text
  label: 'Table header color scheme'
