<?php

/**
 * Implements hook_theme().
 */
function nrfc_fixtures_theme() {
  return [
    'nrfc-fixtures-detail' => [
      'variables' => [
        'team' => [],
        'date' => [],
        'fixture' => [],
      ],
    ],
    'nrfc_fixtures_multiple' => [
      'variables' => [
        'headers' => [],
        'fixtures' => [],
      ],
    ],
    'nrfc_fixtures_team' => [
      'variables' => [
        'fixtures' => [],
      ],
    ],
    'admin.nrfc_fixtures_index' => [
      'variables' => [
        'teams' => [],
      ],
    ],
    'admin.nrfc_fixtures_team' => [
      'variables' => [
        'team' => "team name",
        "upload_form" => NULL,
      ],
      'render element' => 'form',
    ],
  ];
}

